/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'shopId' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'story' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'price' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const CustomOrderRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'shopId' : IDL.Nat,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ProductQueryResponse = IDL.Record({
  'queryResult' : IDL.Opt(IDL.Vec(Product)),
  'error' : IDL.Opt(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'photos' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const Shop = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'announcements' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'categoryId' : IDL.Opt(IDL.Nat),
          'error' : IDL.Opt(IDL.Text),
          'success' : IDL.Bool,
        }),
      ],
      [],
    ),
  'addProduct' : IDL.Func(
      [Product],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [
        IDL.Record({
          'error' : IDL.Opt(IDL.Text),
          'success' : IDL.Bool,
          'reviewId' : IDL.Opt(IDL.Nat),
        }),
      ],
      [],
    ),
  'addShopAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'addToFavorites' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'addToWishlist' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomOrderRequest' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'error' : IDL.Opt(IDL.Text),
          'orderId' : IDL.Opt(IDL.Nat),
          'success' : IDL.Bool,
        }),
      ],
      [],
    ),
  'createShop' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'shopId' : IDL.Opt(IDL.Nat),
          'error' : IDL.Opt(IDL.Text),
          'success' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getMyCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrderRequest)], ['query']),
  'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getMyWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getProductQuery' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [ProductQueryResponse],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReviewsForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getShopCustomOrders' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'orders' : IDL.Opt(IDL.Vec(CustomOrderRequest)),
          'error' : IDL.Opt(IDL.Text),
          'success' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromFavorites' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'removeFromWishlist' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'shopId' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'story' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'price' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const CustomOrderRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'shopId' : IDL.Nat,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ProductQueryResponse = IDL.Record({
    'queryResult' : IDL.Opt(IDL.Vec(Product)),
    'error' : IDL.Opt(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'photos' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const Shop = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'announcements' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'categoryId' : IDL.Opt(IDL.Nat),
            'error' : IDL.Opt(IDL.Text),
            'success' : IDL.Bool,
          }),
        ],
        [],
      ),
    'addProduct' : IDL.Func(
        [Product],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [
          IDL.Record({
            'error' : IDL.Opt(IDL.Text),
            'success' : IDL.Bool,
            'reviewId' : IDL.Opt(IDL.Nat),
          }),
        ],
        [],
      ),
    'addShopAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'addToFavorites' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'addToWishlist' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomOrderRequest' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'error' : IDL.Opt(IDL.Text),
            'orderId' : IDL.Opt(IDL.Nat),
            'success' : IDL.Bool,
          }),
        ],
        [],
      ),
    'createShop' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'shopId' : IDL.Opt(IDL.Nat),
            'error' : IDL.Opt(IDL.Text),
            'success' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getMyCustomOrders' : IDL.Func(
        [],
        [IDL.Vec(CustomOrderRequest)],
        ['query'],
      ),
    'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getMyWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getProductQuery' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [ProductQueryResponse],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReviewsForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getShopCustomOrders' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'orders' : IDL.Opt(IDL.Vec(CustomOrderRequest)),
            'error' : IDL.Opt(IDL.Text),
            'success' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromFavorites' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'removeFromWishlist' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };