/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface CustomOrderRequest {
  'id' : bigint,
  'status' : string,
  'shopId' : bigint,
  'userId' : Principal,
  'description' : string,
  'timestamp' : bigint,
}
export interface Product {
  'id' : bigint,
  'shopId' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'story' : [] | [string],
  'image' : [] | [Uint8Array],
  'price' : bigint,
}
export interface ProductQueryResponse {
  'queryResult' : [] | [Array<Product>],
  'error' : [] | [string],
}
export interface Review {
  'id' : bigint,
  'userId' : Principal,
  'productId' : bigint,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
  'photos' : Array<Uint8Array>,
}
export interface Shop {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'announcements' : Array<string>,
}
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<
    [string],
    {
      'categoryId' : [] | [bigint],
      'error' : [] | [string],
      'success' : boolean,
    }
  >,
  'addProduct' : ActorMethod<
    [Product],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'addReview' : ActorMethod<
    [bigint, bigint, string, Array<Uint8Array>],
    { 'error' : [] | [string], 'success' : boolean, 'reviewId' : [] | [bigint] }
  >,
  'addShopAnnouncement' : ActorMethod<
    [bigint, string],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'addToFavorites' : ActorMethod<
    [bigint],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'addToWishlist' : ActorMethod<
    [bigint],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomOrderRequest' : ActorMethod<
    [bigint, string],
    { 'error' : [] | [string], 'orderId' : [] | [bigint], 'success' : boolean }
  >,
  'createShop' : ActorMethod<
    [string, string],
    { 'shopId' : [] | [bigint], 'error' : [] | [string], 'success' : boolean }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getMyCustomOrders' : ActorMethod<[], Array<CustomOrderRequest>>,
  'getMyFavorites' : ActorMethod<[], Array<bigint>>,
  'getMyWishlist' : ActorMethod<[], Array<bigint>>,
  'getProductQuery' : ActorMethod<
    [string, bigint, bigint],
    ProductQueryResponse
  >,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getReviewsForProduct' : ActorMethod<[bigint], Array<Review>>,
  'getShopCustomOrders' : ActorMethod<
    [bigint],
    {
      'orders' : [] | [Array<CustomOrderRequest>],
      'error' : [] | [string],
      'success' : boolean,
    }
  >,
  'getShops' : ActorMethod<[], Array<Shop>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromFavorites' : ActorMethod<
    [bigint],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'removeFromWishlist' : ActorMethod<
    [bigint],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];