/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProductQueryResponse {
    queryResult?: Array<Product>;
    error?: string;
}
export interface Product {
    id: bigint;
    shopId: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    story?: string;
    image?: Uint8Array;
    price: bigint;
}
export interface Category {
    id: bigint;
    name: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CustomOrderRequest {
    id: bigint;
    status: string;
    shopId: bigint;
    userId: Principal;
    description: string;
    timestamp: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Shop {
    id: bigint;
    owner: Principal;
    name: string;
    description: string;
    announcements: Array<string>;
}
export interface UserProfile {
    bio?: string;
    name: string;
    email?: string;
}
export interface Review {
    id: bigint;
    userId: Principal;
    productId: bigint;
    comment: string;
    timestamp: bigint;
    rating: bigint;
    photos: Array<Uint8Array>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(name: string): Promise<{
        categoryId?: bigint;
        error?: string;
        success: boolean;
    }>;
    addProduct(product: Product): Promise<{
        error?: string;
        success: boolean;
    }>;
    addReview(productId: bigint, rating: bigint, comment: string, photos: Array<Uint8Array>): Promise<{
        error?: string;
        success: boolean;
        reviewId?: bigint;
    }>;
    addShopAnnouncement(shopId: bigint, announcement: string): Promise<{
        error?: string;
        success: boolean;
    }>;
    addToFavorites(shopId: bigint): Promise<{
        error?: string;
        success: boolean;
    }>;
    addToWishlist(productId: bigint): Promise<{
        error?: string;
        success: boolean;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomOrderRequest(shopId: bigint, description: string): Promise<{
        error?: string;
        orderId?: bigint;
        success: boolean;
    }>;
    createShop(name: string, description: string): Promise<{
        shopId?: bigint;
        error?: string;
        success: boolean;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getMyCustomOrders(): Promise<Array<CustomOrderRequest>>;
    getMyFavorites(): Promise<Array<bigint>>;
    getMyWishlist(): Promise<Array<bigint>>;
    getProductQuery(searchText: string, rangeStart: bigint, rangeEnd: bigint): Promise<ProductQueryResponse>;
    getProducts(): Promise<Array<Product>>;
    getProductsByPrice(): Promise<Array<Product>>;
    getReviewsForProduct(productId: bigint): Promise<Array<Review>>;
    getShopCustomOrders(shopId: bigint): Promise<{
        orders?: Array<CustomOrderRequest>;
        error?: string;
        success: boolean;
    }>;
    getShops(): Promise<Array<Shop>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFromFavorites(shopId: bigint): Promise<{
        error?: string;
        success: boolean;
    }>;
    removeFromWishlist(productId: bigint): Promise<{
        error?: string;
        success: boolean;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProducts(searchText: string): Promise<Array<Product>>;
}
import type { CustomOrderRequest as _CustomOrderRequest, Product as _Product, ProductQueryResponse as _ProductQueryResponse, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: string): Promise<{
        categoryId?: bigint;
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: Product): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReview(arg0: bigint, arg1: bigint, arg2: string, arg3: Array<Uint8Array>): Promise<{
        error?: string;
        success: boolean;
        reviewId?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
                return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
            return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addShopAnnouncement(arg0: bigint, arg1: string): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addShopAnnouncement(arg0, arg1);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShopAnnouncement(arg0, arg1);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToFavorites(arg0: bigint): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addToFavorites(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToFavorites(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToWishlist(arg0: bigint): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomOrderRequest(arg0: bigint, arg1: string): Promise<{
        error?: string;
        orderId?: bigint;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomOrderRequest(arg0, arg1);
                return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomOrderRequest(arg0, arg1);
            return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShop(arg0: string, arg1: string): Promise<{
        shopId?: bigint;
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createShop(arg0, arg1);
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShop(arg0, arg1);
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getMyCustomOrders(): Promise<Array<CustomOrderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomOrders();
            return result;
        }
    }
    async getMyFavorites(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFavorites();
            return result;
        }
    }
    async getMyWishlist(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWishlist();
            return result;
        }
    }
    async getProductQuery(arg0: string, arg1: bigint, arg2: bigint): Promise<ProductQueryResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductQuery(arg0, arg1, arg2);
                return from_candid_ProductQueryResponse_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductQuery(arg0, arg1, arg2);
            return from_candid_ProductQueryResponse_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByPrice(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByPrice();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByPrice();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForProduct(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForProduct(arg0);
            return result;
        }
    }
    async getShopCustomOrders(arg0: bigint): Promise<{
        orders?: Array<CustomOrderRequest>;
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopCustomOrders(arg0);
                return from_candid_record_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopCustomOrders(arg0);
            return from_candid_record_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShops();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromFavorites(arg0: bigint): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromFavorites(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromFavorites(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProductQueryResponse_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductQueryResponse): ProductQueryResponse {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Product>]): Array<Product> | null {
    return value.length === 0 ? null : from_candid_vec_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_CustomOrderRequest>]): Array<CustomOrderRequest> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
}): {
    error?: string;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
    reviewId: [] | [bigint];
}): {
    error?: string;
    success: boolean;
    reviewId?: bigint;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        success: value.success,
        reviewId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.reviewId))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    orderId: [] | [bigint];
    success: boolean;
}): {
    error?: string;
    orderId?: bigint;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        orderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.orderId)),
        success: value.success
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shopId: [] | [bigint];
    error: [] | [string];
    success: boolean;
}): {
    shopId?: bigint;
    error?: string;
    success: boolean;
} {
    return {
        shopId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.shopId)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
    email: [] | [string];
}): {
    bio?: string;
    name: string;
    email?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    queryResult: [] | [Array<_Product>];
    error: [] | [string];
}): {
    queryResult?: Array<Product>;
    error?: string;
} {
    return {
        queryResult: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.queryResult)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    shopId: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    story: [] | [string];
    image: [] | [Uint8Array];
    price: bigint;
}): {
    id: bigint;
    shopId: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    story?: string;
    image?: Uint8Array;
    price: bigint;
} {
    return {
        id: value.id,
        shopId: value.shopId,
        name: value.name,
        tags: value.tags,
        description: value.description,
        story: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.story)),
        image: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orders: [] | [Array<_CustomOrderRequest>];
    error: [] | [string];
    success: boolean;
}): {
    orders?: Array<CustomOrderRequest>;
    error?: string;
    success: boolean;
} {
    return {
        orders: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.orders)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: [] | [bigint];
    error: [] | [string];
    success: boolean;
}): {
    categoryId?: bigint;
    error?: string;
    success: boolean;
} {
    return {
        categoryId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.categoryId)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n27(_uploadFile, _downloadFile, x));
}
function to_candid_Product_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    shopId: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    story?: string;
    image?: Uint8Array;
    price: bigint;
}): {
    id: bigint;
    shopId: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    story: [] | [string];
    image: [] | [Uint8Array];
    price: bigint;
} {
    return {
        id: value.id,
        shopId: value.shopId,
        name: value.name,
        tags: value.tags,
        description: value.description,
        story: value.story ? candid_some(value.story) : candid_none(),
        image: value.image ? candid_some(value.image) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    email?: string;
}): {
    bio: [] | [string];
    name: string;
    email: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
